---
version: "2.0"

services:
  app:
    image: dimokus88/peaq:0.0.2
    env:
     - "name=Node_name"
     - "chain=agung" 
     
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 9933
        as: 9933
        to:
          - global: true
      - port: 9944
        as: 9944
        to:
          - global: true
          
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 8Gi
        storage:
          size: 50Gi
  placement:
    akash: 
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
    
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 #max 2 count
